### ISSUE TITLE
Feature request: Support for multiple project folders

### ISSUE THREAD

**Issue by derwaldgeist** [andischerer/atom-svn#12]
I really enjoy this package, it helps a lot, thank you! It would be even better, if it could also support multiple project folders. At the moment, changes are only detected for the first project folder. For other folders, I do not see any highlights. Would be awesome if this could be added. Thanks again for your work, Tom

**Comment by schlinkmumpitz** [comment]
For me it actually supports multiple project folders. But somehow not consequent.

Let's say i have five project folders, all of them svn repos with same svn version etc.
Three of them are recognized as repositories and the svn plugin does its job. The other two folders are not recognized. 
Until now i could not find any pattern how this works because if i remove all folders and add them again, another set of folders is recognized as repository. Sometimes just one of them (mostly the first), sometimes two or three but never all of them.

I know this plugin is early dev state so it is ok, just wanted to report this behaviour. Also thanks for your work :)

**Comment by derwaldgeist** [comment]
Yep, I also found out now that sometimes multiple folders work, but not all of them. Can confirm the behaviour reported by @schlinkmumpitz.

**Comment by davideferre** [comment]
I also confirm that with some project folder it doesn't work, I've tried to close all the project folder and reopen only the one that was not recognized and it continues to do not recognizing it.
